[ERROR] 2021-12-10 00:03:51,431 django.request: Internal Server Error: /profile
Traceback (most recent call last):
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'end'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 482, in thread_handler
    raise exc_info[1]
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\core\handlers\exception.py", line 38, in inner
    response = await get_response(request)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\core\handlers\base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 444, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "c:\users\werkc\appdata\local\programs\python\python39\lib\asyncio\tasks.py", line 440, in wait_for
    return await fut
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 486, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\werkc\Desktop\EasyConnect\EasyConnect\views.py", line 10, in ProfileView
    return render(request, 'profile.html', context)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader_tags.py", line 270, in do_extends
    nodelist = parser.parse()
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader_tags.py", line 213, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\defaulttags.py", line 979, in do_if
    nodelist = parser.parse(('endif',))
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 522, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 82: 'end', expected 'endif'. Did you forget to register or load this tag?
[ERROR] 2021-12-10 00:04:17,642 django.request: Internal Server Error: /profile
Traceback (most recent call last):
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'end'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 482, in thread_handler
    raise exc_info[1]
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\core\handlers\exception.py", line 38, in inner
    response = await get_response(request)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\core\handlers\base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 444, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "c:\users\werkc\appdata\local\programs\python\python39\lib\asyncio\tasks.py", line 440, in wait_for
    return await fut
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 486, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\werkc\Desktop\EasyConnect\EasyConnect\views.py", line 10, in ProfileView
    return render(request, 'profile.html', context)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader_tags.py", line 270, in do_extends
    nodelist = parser.parse()
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader_tags.py", line 213, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\defaulttags.py", line 979, in do_if
    nodelist = parser.parse(('endif',))
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 522, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 82: 'end', expected 'endif'. Did you forget to register or load this tag?
[ERROR] 2021-12-10 00:04:21,680 django.request: Internal Server Error: /profile
Traceback (most recent call last):
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'end'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 482, in thread_handler
    raise exc_info[1]
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\core\handlers\exception.py", line 38, in inner
    response = await get_response(request)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\core\handlers\base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 444, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "c:\users\werkc\appdata\local\programs\python\python39\lib\asyncio\tasks.py", line 440, in wait_for
    return await fut
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 486, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\werkc\Desktop\EasyConnect\EasyConnect\views.py", line 10, in ProfileView
    return render(request, 'profile.html', context)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader_tags.py", line 270, in do_extends
    nodelist = parser.parse()
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader_tags.py", line 213, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\defaulttags.py", line 979, in do_if
    nodelist = parser.parse(('endif',))
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 522, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 82: 'end', expected 'endif'. Did you forget to register or load this tag?
[ERROR] 2021-12-10 00:04:38,389 django.request: Internal Server Error: /profile
Traceback (most recent call last):
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'end'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 482, in thread_handler
    raise exc_info[1]
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\core\handlers\exception.py", line 38, in inner
    response = await get_response(request)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\core\handlers\base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 444, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "c:\users\werkc\appdata\local\programs\python\python39\lib\asyncio\tasks.py", line 440, in wait_for
    return await fut
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 486, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\werkc\Desktop\EasyConnect\EasyConnect\views.py", line 10, in ProfileView
    return render(request, 'profile.html', context)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader_tags.py", line 270, in do_extends
    nodelist = parser.parse()
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader_tags.py", line 213, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\defaulttags.py", line 979, in do_if
    nodelist = parser.parse(('endif',))
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 522, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 82: 'end', expected 'endif'. Did you forget to register or load this tag?
[ERROR] 2021-12-10 00:04:48,872 django.request: Internal Server Error: /profile
Traceback (most recent call last):
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'end'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 482, in thread_handler
    raise exc_info[1]
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\core\handlers\exception.py", line 38, in inner
    response = await get_response(request)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\core\handlers\base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 444, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "c:\users\werkc\appdata\local\programs\python\python39\lib\asyncio\tasks.py", line 440, in wait_for
    return await fut
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 486, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\werkc\Desktop\EasyConnect\EasyConnect\views.py", line 10, in ProfileView
    return render(request, 'profile.html', context)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader_tags.py", line 270, in do_extends
    nodelist = parser.parse()
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader_tags.py", line 213, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\defaulttags.py", line 979, in do_if
    nodelist = parser.parse(('endif',))
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 522, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 82: 'end', expected 'endif'. Did you forget to register or load this tag?
[ERROR] 2021-12-10 00:06:41,993 django.request: Internal Server Error: /profile
Traceback (most recent call last):
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'end'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 482, in thread_handler
    raise exc_info[1]
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\core\handlers\exception.py", line 38, in inner
    response = await get_response(request)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\core\handlers\base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 444, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "c:\users\werkc\appdata\local\programs\python\python39\lib\asyncio\tasks.py", line 440, in wait_for
    return await fut
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 486, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\werkc\Desktop\EasyConnect\EasyConnect\views.py", line 10, in ProfileView
    return render(request, 'profile.html', context)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader_tags.py", line 270, in do_extends
    nodelist = parser.parse()
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader_tags.py", line 213, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\defaulttags.py", line 979, in do_if
    nodelist = parser.parse(('endif',))
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 522, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 82: 'end', expected 'endif'. Did you forget to register or load this tag?
[ERROR] 2021-12-10 00:06:55,145 django.request: Internal Server Error: /profile
Traceback (most recent call last):
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'end'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 482, in thread_handler
    raise exc_info[1]
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\core\handlers\exception.py", line 38, in inner
    response = await get_response(request)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\core\handlers\base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 444, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "c:\users\werkc\appdata\local\programs\python\python39\lib\asyncio\tasks.py", line 440, in wait_for
    return await fut
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 486, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\werkc\Desktop\EasyConnect\EasyConnect\views.py", line 10, in ProfileView
    return render(request, 'profile.html', context)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader_tags.py", line 270, in do_extends
    nodelist = parser.parse()
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader_tags.py", line 213, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\defaulttags.py", line 979, in do_if
    nodelist = parser.parse(('endif',))
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 522, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 82: 'end', expected 'endif'. Did you forget to register or load this tag?
[ERROR] 2021-12-10 00:15:23,339 django.request: Internal Server Error: /profile
Traceback (most recent call last):
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 482, in thread_handler
    raise exc_info[1]
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\core\handlers\exception.py", line 38, in inner
    response = await get_response(request)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\core\handlers\base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 444, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "c:\users\werkc\appdata\local\programs\python\python39\lib\asyncio\tasks.py", line 440, in wait_for
    return await fut
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 486, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\werkc\Desktop\EasyConnect\EasyConnect\views.py", line 10, in ProfileView
    return render(request, 'profile.html', context)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader_tags.py", line 270, in do_extends
    nodelist = parser.parse()
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader_tags.py", line 213, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\defaulttags.py", line 979, in do_if
    nodelist = parser.parse(('endif',))
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ' user.is_superuser' from 'if user.is_superuser'
[ERROR] 2021-12-10 13:17:10,805 django.request: Internal Server Error: /chat/chatchoose/
Traceback (most recent call last):
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 482, in thread_handler
    raise exc_info[1]
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\core\handlers\exception.py", line 38, in inner
    response = await get_response(request)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\core\handlers\base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 444, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "c:\users\werkc\appdata\local\programs\python\python39\lib\asyncio\tasks.py", line 440, in wait_for
    return await fut
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 486, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\werkc\Desktop\EasyConnect\chat\views.py", line 7, in index
    return render(request, 'chat/index.html', {})
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 479, in parse
    self.extend_nodelist(nodelist, compiled_result, token)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 496, in extend_nodelist
    raise self.error(
django.template.exceptions.TemplateSyntaxError: <ExtendsNode: extends 'base.html'> must be the first tag in the template.
[ERROR] 2021-12-10 14:27:28,164 django.request: Internal Server Error: /contact/
Traceback (most recent call last):
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 482, in thread_handler
    raise exc_info[1]
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\core\handlers\exception.py", line 38, in inner
    response = await get_response(request)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\core\handlers\base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 444, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "c:\users\werkc\appdata\local\programs\python\python39\lib\asyncio\tasks.py", line 440, in wait_for
    return await fut
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 486, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\werkc\Desktop\EasyConnect\ContactUs\views.py", line 15, in ContactView
    form.save()
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\forms\models.py", line 452, in save
    raise ValueError(
ValueError: The Contact could not be created because the data didn't validate.
[ERROR] 2021-12-10 14:33:04,211 django.request: Internal Server Error: /profile
Traceback (most recent call last):
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 482, in thread_handler
    raise exc_info[1]
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\core\handlers\exception.py", line 38, in inner
    response = await get_response(request)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\core\handlers\base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 444, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "c:\users\werkc\appdata\local\programs\python\python39\lib\asyncio\tasks.py", line 440, in wait_for
    return await fut
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 486, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\werkc\Desktop\EasyConnect\EasyConnect\views.py", line 10, in ProfileView
    return render(request, 'profile.html', context)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader_tags.py", line 270, in do_extends
    nodelist = parser.parse()
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader_tags.py", line 213, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\defaulttags.py", line 979, in do_if
    nodelist = parser.parse(('endif',))
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '[0]' from 'user.groups[0]'
[ERROR] 2021-12-10 14:33:30,262 django.request: Internal Server Error: /profile
Traceback (most recent call last):
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 482, in thread_handler
    raise exc_info[1]
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\core\handlers\exception.py", line 38, in inner
    response = await get_response(request)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\core\handlers\base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 444, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "c:\users\werkc\appdata\local\programs\python\python39\lib\asyncio\tasks.py", line 440, in wait_for
    return await fut
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 486, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\werkc\Desktop\EasyConnect\EasyConnect\views.py", line 10, in ProfileView
    return render(request, 'profile.html', context)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 988, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 858, in _resolve_lookup
    current = current()
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\db\models\query.py", line 433, in get
    raise self.model.MultipleObjectsReturned(
django.contrib.auth.models.Group.MultipleObjectsReturned: get() returned more than one Group -- it returned 2!
[ERROR] 2021-12-10 14:36:06,399 django.request: Internal Server Error: /chat/chatchoose/
Traceback (most recent call last):
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 482, in thread_handler
    raise exc_info[1]
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\core\handlers\exception.py", line 38, in inner
    response = await get_response(request)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\core\handlers\base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 444, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "c:\users\werkc\appdata\local\programs\python\python39\lib\asyncio\tasks.py", line 440, in wait_for
    return await fut
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 486, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\werkc\Desktop\EasyConnect\chat\views.py", line 7, in index
    return render(request, 'chat/index.html', {})
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ' group in user.groups.all' from 'for group in user.groups.all'
[ERROR] 2021-12-10 14:39:43,768 django.request: Internal Server Error: /chat/chatchoose/
Traceback (most recent call last):
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 482, in thread_handler
    raise exc_info[1]
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\core\handlers\exception.py", line 38, in inner
    response = await get_response(request)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\core\handlers\base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 444, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "c:\users\werkc\appdata\local\programs\python\python39\lib\asyncio\tasks.py", line 440, in wait_for
    return await fut
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\asgiref\sync.py", line 486, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\werkc\Desktop\EasyConnect\chat\views.py", line 7, in index
    return render(request, 'chat/index.html', {})
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\werkc\.virtualenvs\easyconnect-JWSqFyg0\lib\site-packages\django\template\defaulttags.py", line 167, in render
    values = list(values)
TypeError: 'ManyRelatedManager' object is not iterable
[ERROR] 2021-12-12 20:48:07,082 django.request: Internal Server Error: /chat/
Traceback (most recent call last):
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rileymarsden/Desktop/EasyConnect/chat/views.py", line 5, in index
    return render(request, 'index.html', {})
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
[ERROR] 2021-12-12 20:50:27,280 django.request: Internal Server Error: /chat/index/
Traceback (most recent call last):
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rileymarsden/Desktop/EasyConnect/chat/views.py", line 9, in room
    return render(request, 'chatroom.html', {
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: chatroom.html
[ERROR] 2021-12-12 20:52:13,908 django.request: Internal Server Error: /chat/index/
Traceback (most recent call last):
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rileymarsden/Desktop/EasyConnect/chat/views.py", line 9, in room
    return render(request, 'chatroom.html', {
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: chatroom.html
[ERROR] 2021-12-12 20:52:17,618 django.request: Internal Server Error: /chat/
Traceback (most recent call last):
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rileymarsden/Desktop/EasyConnect/chat/views.py", line 5, in index
    return render(request, 'index.html', {})
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
[ERROR] 2021-12-12 20:52:30,415 django.request: Internal Server Error: /chat/chatchoose/
Traceback (most recent call last):
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rileymarsden/Desktop/EasyConnect/chat/views.py", line 9, in room
    return render(request, 'chatroom.html', {
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: chatroom.html
[ERROR] 2021-12-12 20:52:31,485 django.request: Internal Server Error: /chat/choose/
Traceback (most recent call last):
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rileymarsden/Desktop/EasyConnect/chat/views.py", line 5, in index
    return render(request, 'index.html', {})
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
[ERROR] 2021-12-12 20:56:31,508 django.request: Internal Server Error: /chat/choose/
Traceback (most recent call last):
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rileymarsden/Desktop/EasyConnect/chat/views.py", line 5, in index
    return render(request, 'index.html', {})
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
[ERROR] 2021-12-12 20:59:06,660 django.request: Internal Server Error: /chat/chatchoose/
Traceback (most recent call last):
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rileymarsden/Desktop/EasyConnect/chat/views.py", line 9, in room
    return render(request, 'chatroom.html', {
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: chatroom.html
[ERROR] 2021-12-12 20:59:06,831 django.request: Internal Server Error: /chat/choose/
Traceback (most recent call last):
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rileymarsden/Desktop/EasyConnect/chat/views.py", line 5, in index
    return render(request, 'index.html', {})
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
[ERROR] 2021-12-12 21:01:17,205 django.request: Internal Server Error: /chat/helpme/
Traceback (most recent call last):
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rileymarsden/Desktop/EasyConnect/chat/views.py", line 9, in room
    return render(request, 'chatroom.html', {
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: chatroom.html
[ERROR] 2021-12-12 21:12:06,351 django.request: Internal Server Error: /chat/helpme/
Traceback (most recent call last):
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/template/base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rileymarsden/Desktop/EasyConnect/chat/views.py", line 9, in room
    return render(request, 'chat/chatroom.html', {
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/template/base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/rileymarsden/.local/share/virtualenvs/EasyConnect-40Y_jyS5/lib/python3.9/site-packages/django/template/base.py", line 531, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 34: 'static'. Did you forget to register or load this tag?
